### ISSUE TITLE
error form SECURITYTRAILS_GET_SUBDOMAINS

### ISSUE THREAD

**Issue by libralog** [juuso0/CDNRECON#2]
Exception in thread Thread-4 (SECURITYTRAILS_GET_SUBDOMAINS):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Tool/CDNRECON/main.py", line 206, in SECURITYTRAILS_GET_SUBDOMAINS
    REPONSE = REQUEST.get("https://api.securitytrails.com")
NameError: name 'REQUEST' is not defined

**Comment by juuso0** [comment]
Fixed. It was a typo. Thanks for informing.
